insert into vendors values('Angelo''s Organic Natureland','Fruits, Vegitables','Blackburn',3130,'92 South Parade, Blackburn','9877 3030','no details',null,null)
insert into vendors values('Apples and Sage Organic Wholefoods','Wholesale','Balwyn',3103,'371 Whitehorse Road, Balwyn','9836 6132','www.applesandsage.com.au',null,null)
insert into vendors values('Arthur''s Quality Poultry','Meat','South Yarra',3141,'Shop 516, Prahran Market, South Yarra','9824 0408, 0403 229037','www.arthurspoultry.com.au',null,null)
insert into vendors values('Belmore Biodynamic Meats','Meat','Thornbury',3071,'137 Miller Street, Thornbury','9484 0469','www.organicmeatsupply.com.au',null,null)
insert into vendors values('Belmore Meats','Meat','Balwyn',3103,'340 Belmore Road, Balwyn','9857 9379','http://belmoreorganics.com.au/',null,null)
insert into vendors values('Day Kitty','Wholsale','Warrnambool',3280,'52B Kepler Street, Warrnambool','5561 6921','www.facebook.com/daykittycafe',null,null)
insert into vendors values('Di Censo','Meat','Doncaster East',3109,'24 Tunstall Square, Doncaster East','9842 3078','www.dicenso.com.au',null,null)
insert into vendors values('Eastfield Natural Foods','Grocery','Croydon South',3136,'41 The Mall, Croydon South','9723 0257','www.eastfieldnaturalfoods.com',null,null)
insert into vendors values('Garden Organics','Fruits, Vegitables,Grocery, Bakery','Melbourne',3000,'I Shed, Stall 71-77, Queen Victoria Market, Melbourne','8618 6976','www.gardenorganics.com.au',null,null)
insert into vendors values('Gary''s Quality Meats','Meat','South Yarra',3141,'Shop 515, Prahran Market, 163 Commercial Road, South Yarra','9826 0815','www.garysqualitymeats.com.au',null,null)
insert into vendors values('Go Vita','Wholesale','Doncaster',3108,'Shop G200, Westfield Shopping Centre, 619 Doncaster Road, Doncaster','9840 2534','www.govita.com.au',null,null)
insert into vendors values('Go Vita','Wholesale','Epping',3076,'Shop 63, Pacific Epping Shopping Centre, 571-583 High Street, Epping','9408 7779','www.govita.com.au',null,null)
insert into vendors values('Go Vita','Wholesale','Forest Hill',3131,'270 Canterbury Road, Shop 13, Market Place, Forest Hill Chase S/Centre, Forest Hill','9877 5705','www.govita.com.au',null,null)
insert into vendors values('Go Vita','Wholesale','Greensborough',3088,'Level 1, Shop 121A, Greensborough Plaza, 25 Main Street, Greensborough','9432 8401','www.govita.com.au',null,null)
insert into vendors values('Go Vita','Wholesale','Ringwood',3134,'Shop L103, Eastland, Ringwood','9870 2010','www.govita.com.au',null,null)
insert into vendors values('Goldfield Organics','Fruits, Vegitables','Wendouree',3355,'21 Carpenter Street, Wendouree','5339 5449','www.facebook.com/GoldfieldsOrganics',null,null)
insert into vendors values('Hagen''s Organic Meats','Wholesale','Bentleigh',3204,'35 Patterson Road, Bentleigh','9557 0035','www.hagensorganics.com.au',null,null)
insert into vendors values('Hagen''s Organic Meats','Wholesale','Melbourne',3000,'Shop 16, Meat Arcade, Queen Victoria Market, Melbourne','9329 5534','www.hagensorganics.com.au',null,null)
insert into vendors values('Hagen''s Organic Meats','Wholesale','Richmond',3121,'52 Lennox Street, Richmond','9428 2471','www.hagensorganics.com.au',null,null)
insert into vendors values('Hagen''s Organic Meats','Wholesale','South Melbourne',3205,'Stall 1-2, Corner of Cecil and Coventry Streets, South Melbourne','9686 4420','www.hagensorganics.com.au',null,null)
insert into vendors values('Hagen''s Organic Meats','Wholesale','South Yarra',3141,'Shop 509, Prahan Markets, 163 Commercial Road, South Yarra','9827 1899','www.hagensorganics.com.au',null,null)
insert into vendors values('Health Food Thyme','Wholesale','Croydon',3136,'12鈥?4 McAdam Square, Croydon','9725 9907','www.healthfoodthyme.com.au',null,null)
insert into vendors values('Kew Organics','Wholesale','Kew',3101,'Shop 4, 79 Willsmere Road, Kew','9852 8955','www.keworganics.com.au',null,null)
insert into vendors values('Leongatha Health Nutrition & Wholefoods','Wholesale','Leongatha',3953,'21 McCartin Street, Leongatha','5662 2290','www.leongathahealthfoods.com',null,null)
insert into vendors values('Maldon Quality Butchers','Meat','Maldon',3463,'19 Main Street, Maldon','5475 2271','www.facebook.com/MaldonQualityButchers',null,null)
insert into vendors values('Market Organics','Wholesale','Frankston',3199,'32 Yarram Court, Frankston','9329 2493','no details',null,null)
insert into vendors values('Market Organics','Wholesale','Melbourne',3000,'Stall 46-55, Shed, Queen Victoria Market, Melbourne','9328 1425','no details',null,null)
insert into vendors values('Maxi Foods Upper Ferntree Gully','Wholesale','Ferntree Gully',3156,'Ferntree Plaza, Shop 2/1202 Burwood Highway, Ferntree Gully','9243 3777','no details',null,null)
insert into vendors values('Organic Angels','Wholesale','Box Hill South',3128,'PO Box 4009, Box Hill South','9890 0776','www.organicangels.com',null,null)
insert into vendors values('Organic Sunrise','Cafe','Korweinguboora',3461,'39 Horgan Track, Korweinguboora','5348 6501','no details',null,null)
insert into vendors values('Organics Bendigo','Fruits and Vegetables','Bendigo',3550,'320 Lyttleton Terrace, Bendigo','5443 1910','www.organicsbendigo.com.au',null,null)
insert into vendors values('Pachamama Wholefoods','Wholesale','Brunswick',3056,'74-78 Sydney Road, Brunswick','8388 7358','www.pachamamawholefoods.com.au',null,null)
insert into vendors values('Pachamama Wholefoods','Cafe','Brunswick',3056,'74-78 Sydney Road, Brunswick','8388 7358','www.pachamamawholefoods.com.au',null,null)
insert into vendors values('Passionfoods','Wholesale','South Melbourne',3205,'219 Ferrars Street, South Melbourne','9690 9339','www.passionfoods.com.au',null,null)
insert into vendors values('Plump Organic Grocery','Wholesale','Yarraville',3013,'24 Ballarat Street, Yarraville','9687 6422','www.plump.com.au',null,null)
insert into vendors values('Red Beard','Bakery','Trentham',3458,'38A High Street, Trentham','5424 1002','www.redbeardbakery.com.au',null,null)
insert into vendors values('Rendina''s Butchery Biodynamic & Organic Meats','Meat','Balwyn',3104,'253b Belmore Road, Balwyn','9857 6669','www.rendinasbutchery.com.au',null,null)
insert into vendors values('Supa IGA East Ringwood','Wholesale','Ringwood East',3135,'84-92 East Railway Avenue, Ringwood East','9870 8893','no details',null,null)
insert into vendors values('Surfcoast Wholefoods','Wholesale','Torquay',3228,'Shop 104, 41 Bristol Road, Torquay','5261 5555','www.surfcoastwholefoods.com.au',null,null)
insert into vendors values('The Little Hen','Wholesale','Balaclava',3183,'270-272 Carlisle Street, Balaclava','9534 6588','www.thelittlehen.com.au',null,null)
insert into vendors values('The Morning Harvest','Wholesale','Sunbury',3429,'55 Evans Street, Sunbury','9746 3251','www.facebook.com/TheMorningHarvest',null,null)
