//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quiz
    {
        public int id { get; set; }
        public int grade { get; set; }
        public Nullable<int> count { get; set; }
    }
}
