//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IE_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public decimal Longitude { get; set; }
        public decimal latitude { get; set; }
        public string Name { get; set; }
        public string category { get; set; }
        public string suburb { get; set; }
        public decimal postcode { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string website { get; set; }
    }
}
